[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
build = 'yarn install --frozen-lockfile'
hook_add = '''

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
function! SetMyCocKeyMap()
  nmap gd <Plug>(coc-definition)
  nmap <F7> <Plug>(coc-codeaction)
  nnoremap <silent> K :call <SID>show_documentation()<CR>
endfunction
autocmd User CocNvimInit call SetMyCocKeyMap()
autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
set statusline^=%{coc#status()}
'''

[[plugins]]
repo = "neoclide/coc-denite"
