[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
build = 'yarn install --frozen-lockfile'
hook_add = '''
function! s:SetCocKeyMap()
  nmap gd <Plug>(coc-definition)
endfunction
autocmd User CocNvimInit call s:SetCocKeyMap()
autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
'''

[[plugins]]
repo = "neoclide/coc-denite"
