# UI
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
[plugins.ftplugin]
ddu-ff = '''
  nnoremap <buffer> <CR>
  \ <Cmd>call ddu#ui#do_action('itemAction')<CR>
  nnoremap <buffer> <Space>
  \ <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
  nnoremap <buffer> *
  \ <Cmd>call ddu#ui#do_action('toggleAllItems')<CR>
  nnoremap <buffer> i
  \ <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
  nnoremap <buffer> <C-l>
  \ <Cmd>call ddu#ui#do_action('refreshItems')<CR>
  nnoremap <buffer> p
  \ <Cmd>call ddu#ui#do_action('previewPath')<CR>
  nnoremap <buffer> P
  \ <Cmd>call ddu#ui#do_action('preview')<CR>
  nnoremap <buffer> q
  \ <Cmd>call ddu#ui#do_action('quit')<CR>
  nnoremap <buffer> <C-h>
  \ <Cmd>call ddu#ui#do_action('quit')<CR>
  nnoremap <buffer> a
  \ <Cmd>call ddu#ui#do_action('chooseAction')<CR>
  nnoremap <buffer> o
  \ <Cmd>call ddu#ui#do_action('expandItem',
  \ #{ mode: 'toggle' })<CR>
  nnoremap <buffer> d
  \ <Cmd>call ddu#ui#do_action('itemAction',
  \ b:ddu_ui_name ==# 'filer' ? #{ name: 'trash' } : #{ name: 'delete' })<CR>
  nnoremap <buffer> e
  \ <Cmd>call ddu#ui#do_action('itemAction',
  \ #{ name: 'edit' })<CR>
  nnoremap <buffer> E
  \ <Cmd>call ddu#ui#do_action('itemAction',
  \ #{ params: eval(input('params: ')) })<CR>
  nnoremap <buffer> v
  \ <Cmd>call ddu#ui#do_action('itemAction',
  \ #{ name: 'open', params: #{ command: 'vsplit' } })<CR>
  nnoremap <buffer> N
  \ <Cmd>call ddu#ui#do_action('itemAction',
  \ b:ddu_ui_name ==# 'file' ? #{ name: 'newFile' } : #{ name: 'new' })<CR>
  nnoremap <buffer> r
  \ <Cmd>call ddu#ui#do_action('itemAction', #{ name: 'quickfix' })<CR>
  nnoremap <buffer> yy
  \ <Cmd>call ddu#ui#do_action('itemAction', #{ name: 'yank' })<CR>
  nnoremap <buffer> gr
  \ <Cmd>call ddu#ui#do_action('itemAction', #{ name: 'grep' })<CR>
  nnoremap <buffer> n
  \ <Cmd>call ddu#ui#do_action('itemAction', #{ name: 'narrow' })<CR>

  xnoremap <silent><buffer> <Space>
  \ :call ddu#ui#do_action('toggleSelectItem')<CR>

  " Switch options
  nnoremap <buffer> u
  \ <Cmd>call ddu#ui#do_action('updateOptions', #{
  \   sourceOptions: #{
  \     _: #{
  \       matchers: [],
  \     },
  \   },
  \ })<CR>

  " Switch sources
  nnoremap <buffer> ff
  \ <Cmd>call ddu#ui#do_action('updateOptions', #{
  \   sources: [
  \     #{ name: 'file' },
  \   ],
  \ })<CR>
'''
ddu-ff-filter = '''
  inoremap <buffer> <CR>
  \ <Esc><Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
  nnoremap <buffer> <CR>
  \ <Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
'''

# Sources
[[plugins]]
repo = 'Shougo/ddu-source-action'

[[plugins]]
repo = '4513ECHO/ddu-source-source'
lua_source = '''
vim.fn['ddu#custom#patch_global']('kindOptions', {
  source={
    defaultAction='execute'
  }
})
'''

[[plugins]]
repo = '4513ECHO/ddu-source-colorscheme'

# Filter
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
lua_source = '''
vim.fn['ddu#custom#patch_global']('filterParams', {
  matcher_substring={
    highlightMatched='Search'
  }
})
'''

# Kinds

# Miscs
[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'
