[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-lua/lsp-status.nvim'
hook_source = '''
  function! LspStatus() abort
    if luaeval('#vim.lsp.buf_get_clients() > 0')
      return luaeval("require('lsp-status').status()")
    endif
    return ''
  endfunction
'''

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = ['plenary.nvim']

[[plugins]]
repo = 'davidosomething/format-ts-errors.nvim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
# actually, nvim-lsp config don't require null-ls
# This allows set null-ls settings in lsp settings
depends = ['lsp-status.nvim', 'null-ls.nvim', 'format-ts-errors.nvim']
on_event = ['BufRead', 'BufNewFile']
hook_source = '''
  lua _G.virus_lsp_settings()
'''
