[[plugins]]
on_ft = ["typescript", "typescriptreact", "vue"]
repo = "HerringtonDarkholme/yats.vim"

[[plugins]]
repo = "othree/html5.vim"
on_ft = ["html", "vue"]

[[plugins]]
repo = "hail2u/vim-css3-syntax"
on_ft = ["css", "vue"]

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
hook_source = '''
autocmd FileType javascript setlocal indentkeys+=.
autocmd FileType javascript setlocal foldmethod=syntax
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
hook_add = """
autocmd FileType vue syntax sync fromstart
"""

[[plugins]]
repo = "MaxMEllon/vim-jsx-pretty"
on_ft = ["javascript", "jsx"]

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# SPARQL
[[plugins]]
repo = 'atextor/sparql.vim'
on_ft = 'sparql'
