[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
rev = 'main'
lazy = 1
on_event = ['BufRead', 'CursorHold', 'FileType']
hook_post_update = 'TSUpdate'
hook_post_source = '''
lua <<EOF
local treesitter = require'nvim-treesitter'
treesitter.setup {
  install_dir = vim.fn.stdpath('data') .. '/site'
}

treesitter.install {
  'javascript',
  'rust',
  'slim',
  'toml',
  'tsx',
  'typescript',
  'vim',
  'vimdoc',
  'yaml',
}

local augroup = "VirusTSAugroup"

vim.api.nvim_create_augroup(augroup, {
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = {
    'help',
    'javascript',
    'rust',
    'slim',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'yaml',
  },
  callback = function()
    vim.treesitter.start()
    vim.wo.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
    vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
  end
})

'''

[[plugins]]
repo = 'cshuaimin/ssr.nvim'
depends = ['nvim-treesitter']
lazy = 1
on_source = ['nvim-treesitter']
lua_add = '''
vim.keymap.set({ "n", "x" }, "<leader>sr", function() require("ssr").open() end)
'''
lua_source = '''
require("ssr").setup {
  border = "rounded",
  min_width = 50,
  min_height = 5,
  max_width = 120,
  max_height = 25,
  keymaps = {
    close = "q",
    next_match = "n",
    prev_match = "N",
    replace_confirm = "<cr>",
    replace_all = "<leader><cr>",
  },
}
'''

[[plugins]]
repo = 'bennypowers/nvim-regexplainer'
depends = ['nvim-treesitter', 'nui.nvim']
lazy = 1
on_source = ['nvim-treesitter']
lua_source = '''
require'regexplainer'.setup()
'''
