[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
lazy = 1
on_event = ['BufRead', 'CursorHold', 'FileType']
hook_post_update = 'TSUpdate'
hook_post_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  -- Modules and its options go here
  ensure_installed = "all",
  highlight = { enable = true },
  incremental_selection = { enable = true },
  textobjects = { enable = true },
  indent = {
    enable = true,
  },
}
EOF
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
'''

[[plugins]]
repo = 'cshuaimin/ssr.nvim'
depends = ['nvim-treesitter']
lazy = 1
on_source = ['nvim-treesitter']
lua_add = '''
vim.keymap.set({ "n", "x" }, "<leader>sr", function() require("ssr").open() end)
'''
lua_source = '''
require("ssr").setup {
  border = "rounded",
  min_width = 50,
  min_height = 5,
  max_width = 120,
  max_height = 25,
  keymaps = {
    close = "q",
    next_match = "n",
    prev_match = "N",
    replace_confirm = "<cr>",
    replace_all = "<leader><cr>",
  },
}
'''

[[plugins]]
repo = 'bennypowers/nvim-regexplainer'
depends = ['nvim-treesitter', 'nui.nvim']
lazy = 1
on_source = ['nvim-treesitter']
lua_source = '''
require'regexplainer'.setup()
'''
