# utils

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'previm/previm'
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'

## denite
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
rev = 'master'
hook_add = '''
nmap <Plug>[Space]<Space> :<C-u>Denite menu<CR>
nmap <Plug>[Space]db :<C-u>Denite buffer<CR>

nnoremap <silent> <C-p> :<C-u>Denite
      \ `finddir('.git', ';') != '' ? 'file/rec/git' : 'file/rec'`<CR>

" Define mappings
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
        \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
        \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
        \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
        \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
        \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
        \ denite#do_map('toggle_select').'j'
  nnoremap <silent><buffer><expr> <Tab>
        \ denite#do_map('choose_action')
endfunction
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
depends = 'denite.nvim'

[[plugins]]
repo = 'kmnk/denite-dirmark'
on_source = 'denite.nvim'

[[plugins]]
repo = 'pocari/vim-denite-emoji'
on_source = 'denite.nvim'

[[plugins]]
repo = 'skk-dev/dict'
name = 'skk-dict'

[[plugins]]
repo = 'vim-skk/skkeleton'
on_map = {ic = '<Plug>(skkeleton-toggle)'}
depends = ['denops.vim', 'skk-dict']
hook_add = '''
  imap <C-j> <Plug>(skkeleton-toggle)
  cmap <C-j> <Plug>(skkeleton-toggle)
'''
hook_source = '''
let s:dict_location = dein#get('skk-dict')['path']
call skkeleton#config(#{
  \ globalDictionaries: [
  \     expand(s:dict_location .. '/SKK-JISYO.L')
  \ ]
  \ })
'''

[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_source = 'denops.vim'
lua_source = '''
vim.fn['ddu#custom#patch_global']({
  ui='ff'
})
'''
