# utils

[[plugins]]
if = 'has("python3")'
repo = "Shougo/deoplete.nvim"
depends = ["context_filetype.vim"]
on_event = "InsertEnter"
hook_add="""
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#omni#input_patterns = {
        \   "ruby" : '[^. *\t]\.\w*\|\h\w*::',
        \}
"""

# html/css

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','css','htmldjango','vue', 'pug', "eruby"]
hook_source = '''
let g:user_emmet_settings = {
\ 'variables': {
\  'lang': 'ja',
\ },
\ 'vue': {
\  'filters': 'html',
\ }
\}
'''

[[plugins]]
repo = "othree/html5.vim"
on_ft = ["html", "vue"]

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ["pug", "vue"]

[[plugins]]
repo = 'nikvdp/ejs-syntax'
on_ft = ["ejs"]

# javascript

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'vue']
hook_source = '''
autocmd FileType javascript setlocal indentkeys+=.
autocmd FileType javascript setlocal foldmethod=syntax
'''

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'vue']

[[plugins]]
repo = 'ternjs/tern_for_vim'
on_ft = ['javascript', 'vue']
if = 'executable("npm")'
build = 'npm install'
hook_source = '''
autocmd FileType javascript setlocal completeopt=menuone,preview
autocmd FileType javascript map <buffer> <C-]> :TernDef
'''

[[plugins]]
repo = "carlitux/deoplete-ternjs"
on_ft = ["javascript", "vue"]
hook_add = """
let g:deoplete#sources#ternjs#filetypes = ['vue']
let g:tern#command = ["tern"]
let g:tern#arguments = ["--persistent"]
"""

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
on_ft = ["typescript", "vue"]
repo = "leafgarland/typescript-vim"
hook_source = '''
autocmd FileType typescript setlocal indentkeys+=0.
'''

# [[plugins]]
# on_ft = ["typescript", "vue"]
# repo = "HerringtonDarkholme/yats.vim"

[[plugins]]
if = "has('nvim')"
repo = 'mhartington/nvim-typescript'
on_ft = ['typescript', 'vue']
hook_source = '''
let g:nvim_typescript#vue_support = 1
'''

# python

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
build = 'git submodule update --init --recursive'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
hook_add = '''
let g:virtualenv_auto_activate = 1
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = [ "Shougo/deoplete.nvim"]
on_ft = ["python"]
if = 'has("nvim")'

# go

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

# ruby

[[plugins]]
repo = "vim-ruby/vim-ruby"
on_ft = ["ruby"]

[[plugins]]
on_ft = ["ruby", "eruby"]
repo = "tpope/vim-rails"

[[plugins]]
on_ft = ["ruby"]
repo = "tpope/vim-bundler"

[[plugins]]
repo = "uplus/deoplete-solargraph"
on_ft = ["ruby", "eruby"]

[[plugins]]
repo = "5t111111/denite-rails"
on_ft = ["ruby", "eruby"]

# Lisp

[[plugins]]
on_ft = ["lisp"]
repo = "l04m33/vlime"
rtp = "vim/"

# SPARQL/RDF

[[plugins]]
repo = 'nikolavp/sparql.vim'
on_ft = 'sparql'

[[plugins]]
repo = 'niklasl/vim-rdf'

# Swift/iOS

[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]]
if = 'has("nvim")'
depends = ["Shougo/deoplete.nvim"]
repo = 'mitsuse/autocomplete-swift'

# Other

[[plugins]]
repo = 'vim-scripts/nginx.vim'
on_ft = ['nginx']

[[plugins]]
repo = "chrisbra/csv.vim"

[[plugins]]
repo = 'kylef/apiblueprint.vim'
on_ft = ["apiblueprint"]
hook_add = '''
autocmd FileType apiblueprint setlocal tabstop=4 softtabstop=4 shiftwidth=4
'''
