# html/css

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','css','htmldjango']

# javascript

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript']

[[plugins]]
repo = 'ternjs/tern_for_vim'
on_ft = 'javascript'
build = 'npm install | tee'
hook_source = '''
autocmd FileType javascript setlocal completeopt=menuone,preview
'''

# python

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
build = 'git submodule update --init --recursive'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
