[[plugins]]
repo = 'Shougo/dein.vim'

# core
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
if = '!has("nvim") && has("python3")'
repo = "roxma/nvim-yarp"

[[plugins]]
if = '!has("nvim") && (has("python") || has("python3"))'
repo = "roxma/vim-hug-neovim-rpc"

# util
[[plugins]]
repo = 'sjl/gundo.vim'
if = 'has("python") || has("python3")'
hook_add = '''
if has("python3")
 let g:gundo_prefer_python3 = 1
endif
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/Unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
lazy = 1
on_cmd = 'Denite'

hook_source = '''
call denite#custom#option('default', {
   \ 'mode': 'normal',
   \ 'direction': 'dynamictop'
   \})
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'Unite.vim'
hook_add = '''
"call vimfiler#custom#profile('default', 'context', {
"  \ 'safe' : 0,
"  \})
   nmap <F3> :VimFiler -simple -winwidth=30 -toggle -buffer-name=explorer -split -no-quit<CR>
'''

[[plugins]]
repo = 'Shougo/unite-outline'
depends = 'Unite.vim'

# help doc
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# filetypes
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# colorscheme
[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'nikolavp/sparql.vim'
on_ft = 'sparql'

[[plugins]]
repo = 'niklasl/vim-rdf'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'

[[plugins]]
repo = 'w0rp/ale'
hook_add = """
let g:ale_lint_on_filetype_changed = 0
let g:ale_lint_on_text_changed = "never"
let g:ale_linters = {
      \ "vue" : ["eslint"]
      \}
let g:ale_fixers = {
      \ 'javascript': [
  \       'eslint'
  \   ],
      \ 'typescript': [
  \       'eslint'
  \   ],
      \ 'vue': [
  \       'eslint'
  \   ],
  \}
"""

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
hook_add = """
let g:precious_enable_switchers = {
      \ "*" : {
      \         "setfiletype": 1
      \ },
      \ "vue" : {
      \         "setfiletype": 0
      \ },
      \}
" let g:precious_enable_switch_CursorMoved = {
"       \	"vue" : 0
"       \}
" let g:precious_enable_switch_CursorMoved_i = {
"       \	"vue" : 0
"       \}
"augroup MyDeinPrecious
"  autocmd!
"  autocmd InsertEnter *.vue :PreciousSwitch
"  autocmd InsertLeave *.vue :PreciousReset
"augroup END
"""

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'thinca/vim-quickrun'
