[[plugins]]
repo = 'Shougo/dein.vim'

# util
[[plugins]]
repo = 'sjl/gundo.vim'
if = 'has("python") || has("python3")'
hook_add = '''
if has("python3")
 let g:gundo_prefer_python3 = 1
endif
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/Unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
call denite#custom#option('default', {
   \ 'mode': 'normal',
   \ 'direction': 'dynamictop'
   \})
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'Shougo/Unite.vim'
hook_add = '''
"call vimfiler#custom#profile('default', 'context', {
"  \ 'safe' : 0,
"  \})
   nmap <F3> :VimFiler -simple -winwidth=30 -toggle -buffer-name=explorer -split -no-quit<CR>
'''

[[plugins]]
repo = 'Shougo/unite-outline'
depends = 'Shougo/Unite.vim'

# help doc
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# filetypes
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# colorscheme
[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'nikolavp/sparql.vim'
on_ft = 'sparql'

[[plugins]]
repo = 'niklasl/vim-rdf'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'

# [[plugins]]
# repo = 'neomake/neomake'
# hook_add = '''
# let g:neomake_javascript_enabled_makers = ['eslint']
# augroup MyNeomakeGroup
#  autocmd!
#  autocmd BufWritePost * Neomake
# augroup END
# '''

# [[plugins]]
# repo = 'benjie/neomake-local-eslint.vim'
# depends = 'neomake/neomake'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'Shougo/context_filetype.vim'
