# html/css

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','css','htmldjango','vue']
hook_source = '''
let g:user_emmet_settings = {
\ 'variables': {
\  'lang': 'ja',
\ },
\ 'vue': {
\  'filters': 'html',
\ }
\}
'''

# javascript

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'vue']
hook_source = '''
autocmd FileType javascript setlocal indentkeys+=.
'''

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'vue']

[[plugins]]
repo = 'ternjs/tern_for_vim'
on_ft = ['javascript', 'vue']
build = 'npm install'
hook_source = '''
autocmd FileType javascript setlocal completeopt=menuone,preview
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

# python

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
build = 'git submodule update --init --recursive'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
