[[plugins]]
repo = 'Shougo/dein.vim'

# util
[[plugins]]
repo = 'sjl/gundo.vim'
if = "has('python')"

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/Unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'Shougo/Unite.vim'
hook_add = '''
call vimfiler#custom#profile('default', 'context', {
  \ 'safe' : 0,
\})
nmap <F3> :VimFiler -simple -winwidth=30 -toggle -buffer-name=explorer -split -no-quit<CR>
'''

# help doc
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# filetypes
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'nikolavp/sparql.vim'
on_ft = 'sparql'

[[plugins]]
repo = 'niklasl/vim-rdf'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'
