# utils

[[plugins]]
if = 'has("python3")'
repo = "Shougo/deoplete.nvim"
depends = ["context_filetype.vim"]
on_event = "InsertEnter"
hook_add="""
let g:deoplete#enable_at_startup = 1
"""

# html/css

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','css','htmldjango','vue']
hook_source = '''
let g:user_emmet_settings = {
\ 'variables': {
\  'lang': 'ja',
\ },
\ 'vue': {
\  'filters': 'html',
\ }
\}
'''

# javascript

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'vue']
hook_source = '''
autocmd FileType javascript setlocal indentkeys+=.
autocmd FileType javascript setlocal foldmethod=syntax
'''

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'vue']

[[plugins]]
repo = 'ternjs/tern_for_vim'
on_ft = ['javascript', 'vue']
if = 'executable("npm")'
build = 'npm install'
hook_source = '''
autocmd FileType javascript setlocal completeopt=menuone,preview
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
on_ft = ["typescript"]
repo = "leafgarland/typescript-vim"

[[plugins]]
on_ft = ["typescript"]
repo = "HerringtonDarkholme/yats.vim"

[[plugins]]
if = "has('nvim')"
repo = 'mhartington/nvim-typescript'
on_ft = ['typescript', 'vue']
hook_source = '''
let g:nvim_typescript#vue_support = 1
'''

# python

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
build = 'git submodule update --init --recursive'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
hook_add = '''
let g:virtualenv_auto_activate = 1
'''

# go

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
